const CityList = [
  {
    id: "1",
    name: "Bangalore",
    desc: "Clear with periodic clouds",
    temp: "25 °C",
    humidity: "52.0%",
  },
  {
    id: "2",
    name: "Mumbai",
    desc: "Clear with periodic clouds",
    temp: "28 °C",
    humidity: "82.0%",
  },
  {
    id: "3",
    name: "Pune",
    desc: "Clear with periodic clouds",
    temp: "22 °C",
    humidity: "56.0%",
  },
  {
    id: "4",
    name: "Patna",
    desc: "Clear with periodic clouds",
    temp: "26 °C",
    humidity: "54.0%",
  },
  {
    id: "5",
    name: "Delhi",
    desc: "Clear with periodic clouds",
    temp: "30 °C",
    humidity: "58.0%",
  },
  {
    id: "6",
    name: "Kolkata",
    desc: "Clear with periodic clouds",
    temp: "29 °C",
    humidity: "72.0%",
  },
  {
    id: "7",
    name: "Punjab",
    desc: "Clear with periodic clouds",
    temp: "18 °C",
    humidity: "59.0%",
  },
  {
    id: "8",
    name: "Rajasthan",
    desc: "Clear with periodic clouds",
    temp: "31 °C",
    humidity: "32.0%",
  },
  {
    id: "9",
    name: "Surat",
    desc: "Clear with periodic clouds",
    temp: "29 °C",
    humidity: "72.0%",
  },
  {
    id: "10",
    name: "Ranchi",
    desc: "Clear with periodic clouds",
    temp: "20 °C",
    humidity: "52.0%",
  },
  {
    id: "11",
    name: "Chennai",
    desc: "Clear with periodic clouds",
    temp: "20 °C",
    humidity: "52.0%",
  },
  {
    id: "12",
    name: "Jaipur",
    desc: "Clear with periodic clouds",
    temp: "20 °C",
    humidity: "52.0%",
  },
];

export default CityList;
